### ISSUE TITLE
Ok button doesn't seem to do anything

### ISSUE THREAD

**Issue by AaronSadlerUK** [NikRimington/HotChilli.Umbraco.PageNotFoundManager#1]
On the confirmation screen after setting the not found page, the Ok button doesn't close the blade.

![image](https://user-images.githubusercontent.com/9937803/128345972-0aea61fc-1d64-4003-8e5d-87d0ad4513a3.png)

**Comment by NikRimington** [comment]
Hey @AaronSadlerUK thanks for raising this, it's been resolved now and beta 4 should now be available.
