### ISSUE TITLE
The icon in the context menu seems like something is wrong

### ISSUE THREAD

**Issue by FransdeJong** [NikRimington/HotChilli.Umbraco.PageNotFoundManager#10]
The icon in the context menu seems like something is wrong with this option.
Maybe this can be a less "aggressive" icon? Or is there a reason for being a warning icon?

![image](https://user-images.githubusercontent.com/29602162/157472393-2f1bd3a5-094d-4584-821e-2d743e60fa85.png)

**Comment by NikRimington** [comment]
Hey @FransdeJong 

There is no reason for it being a warning icon other than when I was setting it I felt it was the closest icon that represented 404.
I'm happy for suggestions of an alternative icon and colour suggestion (it could be black, I just wanted to use colour so it stood out from being a standard Umbraco menu option).

What Icon do you think would be better? :-)

**Comment by FransdeJong** [comment]
I understand your reasoning, but my colleague asked me if it was safe to click on it 🤣.
I'm wondering if a custom icon is possible in this place? If so we could provide a 404 icon.


________________________________

**Comment by NikRimington** [comment]
I've changed the icon and the colour, sorry it's taken so long :-)

**Comment by FransdeJong** [comment]
Absolutely no need to say sorry. If you would have said I like red it was fine to.
Your package so you can do whatever and when you want 🙏
