### ISSUE TITLE
Accidentally removes setting, if a 404 page is already set

### ISSUE THREAD

**Issue by skttl** [NikRimington/HotChilli.Umbraco.PageNotFoundManager#12]
Not sure how to describe this perfectly but was testing out the package on the starter kit and had set the 404 page for the home page to a page. When opening the 404-page dialog afterwards, it looked broken, and I couldn't select a 404 page, I only had the one chosen available, but I couldn't even select that one.

Upon clicking ok, the 404-page setting got removed. I've recorded a gif of it:
![22-05-21---21-03-36---948---zWiAnX5RKn](https://user-images.githubusercontent.com/3726467/169665951-7f2390ee-3ba7-4ae4-8a85-9abcc352656a.gif)

**Comment by NikRimington** [comment]
Ohh nice find, that's really odd, I know the UI needs a bit of improvement. I have a couple of ideas on it. I think currently clicking the node removes it because it acts the same as clicking the little red cross.

**Comment by NikRimington** [comment]
Hey @skttl I've got a fix for this which I've now merged. Thanks for finding it!

**Comment by NikRimington** [comment]
This fix is available with release 1.1.0 which is waiting for NuGet to index it :-)
