### ISSUE TITLE
Update from v2.0.0 to 2.1.0 causes BootFailedException: "Conflicting routes, you cannot have multiple controllers with the same name: MenuController"

### ISSUE THREAD

**Issue by hfloyd** [NikRimington/HotChilli.Umbraco.PageNotFoundManager#23]
Just updated this via NuGet and now get this error:

`BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details. -> Umbraco.Cms.Core.Exceptions.BootFailedException: Conflicting routes, you cannot have multiple controllers with the same name: MenuController`

Reverting the update resolves the issue.

## Info: ##

Umbraco version 10.2.1

All packages installed:

```
	<PackageReference Include="Cultiv.EnvironmentInspect" Version="1.0.1" />
	<PackageReference Include="Dawoe.OEmbedPickerPropertyEditor" Version="10.0.0" />
	<PackageReference Include="Dawoe.OEmbedPickerPropertyEditor.Core" Version="10.0.0" />
	<PackageReference Include="Diplo.GodMode" Version="10.2.0" />
	<PackageReference Include="Dragonfly.Umbraco10.Forms.Web" Version="0.0.17" />
	<PackageReference Include="Dragonfly.Umbraco10.SchemaImporter" Version="0.2.0" />
	<PackageReference Include="Dragonfly.Umbraco10.SiteAuditor" Version="0.0.2" />
	<PackageReference Include="Dragonfly.Umbraco10.Theming.Web" Version="0.2.3" />
	<PackageReference Include="HotChilli.Umbraco.PageNotFound" Version="2.0.0" />
	<PackageReference Include="Limbo.Umbraco.ModelsBuilder" Version="2.0.0-alpha002" />
	<PackageReference Include="Our.Iconic" Version="4.0.0" />
	<PackageReference Include="Our.Umbraco.Community.Contentment" Version="4.1.5" />
	<PackageReference Include="Our.Umbraco.Community.Contentment.Core" Version="4.1.5" />
	<PackageReference Include="Our.Umbraco.SimpleTreeMenu" Version="3.0.0" />
	<PackageReference Include="Our.Umbraco.Skipper" Version="1.1.3" />
	<PackageReference Include="Umbraco.Cloud.Identity.Cms" Version="10.0.4" />
	<PackageReference Include="Umbraco.Cloud.StorageProviders.AzureBlob" Version="10.0.0" />
	<PackageReference Include="Umbraco.Cms" Version="10.2.1" />
	<PackageReference Include="Umbraco.Deploy.Cloud" Version="10.1.0" />
	<PackageReference Include="Umbraco.Deploy.Contrib" Version="10.1.0" />
	<PackageReference Include="Umbraco.Deploy.Forms" Version="10.1.0" />
	<PackageReference Include="Umbraco.Forms" Version="10.1.2" />
```

**Comment by NikRimington** [comment]
Hey Heather,

Thanks for reporting this. Can you try deleting any page not found DLLs from your bin directory and deleting the page not found folder in app plugins. The release probably should have been a major version rather than a minor as it was a change to an RCL and the removal of the .core project.

**Comment by hfloyd** [comment]
Also, if you have a .targets file, you can make sure it deletes the App_Plugins on rebuild... 

example : https://github.com/hfloyd/Dragonfly.Umbraco10.SchemaImporter/blob/master/src/Dragonfly/build/Dragonfly.Umbraco10.SchemaImporter.targets#L18

You might have this, but I didn't see it in your repo (default .gitignore seem to automatically exclude the 'build' folder)

**Comment by hfloyd** [comment]
I figured out the issue - I was using the "Update" pane in the Nuget UI, and didn't noticed that there was a **second separate package** installed, which didn't get un-installed on update (because it was referenced by my separate "cs-only" project):

![image](https://user-images.githubusercontent.com/1252593/194670414-20b5b1dd-a74c-459d-8354-6ea7f3ba8cdd.png)

After uninstalling "HotChilli.Umbraco.PageNotFound.Core v.2.0", then [Rebuild Solution], restart the local site in IIS... and NO ERROR!

Thanks for the troubleshooting help!
