### ISSUE TITLE
Not supported in .Net 7.0

### ISSUE THREAD

**Issue by henryson** [NikRimington/HotChilli.Umbraco.PageNotFoundManager#25]
I use this package and try to upgrade Umbraco to 11+ 
But it seems to fail because this package is in .Net 6.0.
Will there be a new version of this that runs in .Net 7.0?

**Comment by NikRimington** [comment]
Hey @henryson ,

I've not had a chance to re-compile it against .Net 7, but I plan to :-) It should just be a case of recompiling and changing the Umbraco dependencies.

**Comment by henryson** [comment]
@NikRimington any progress on this? Cheers /Josef

**Comment by AaronSadlerUK** [comment]
@NikRimington I think this was fixed with the version 13 support?

**Comment by NikRimington** [comment]
This was resolved in version 2.2.0
https://github.com/NikRimington/HotChilli.Umbraco.PageNotFoundManager/releases/tag/2.2.0
